In [107]:
import pandas as pd

In [108]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
series=pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [109]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['c0','c1','c2'],index=['r0','r1','r2'])
print(df)

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

In [110]:
obesity_data=pd.read_csv('/content/obesity_prediction.csv')
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [111]:
obesity_data.tail()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [112]:
obesity_data.sample()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
846,Female,21.0,1.754497,77.956921,yes,yes,2.446872,2.372311,Sometimes,no,1.81031,no,0.094893,1.650778,Sometimes,Public_Transportation,Overweight_Level_I

In [113]:
obesity_data.sample(10,random_state=29)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
631,Female,19.272573,1.713670,50.000000,no,yes,1.005578,4.000000,Frequently,no,1.000000,no,1.683957,0.704978,Sometimes,Public_Transportation,Insufficient_Weight
1216,Female,42.316070,1.583943,81.936398,yes,yes,2.490507,2.974204,Sometimes,no,1.846754,no,0.000000,0.000000,no,Automobile,Obesity_Type_I
1321,Female,23.000000,1.608469,82.954796,yes,yes,2.150054,2.988539,Sometimes,no,2.768325,no,2.085150,0.000000,no,Public_Transportation,Obesity_Type_I
1844,Female,26.000000,1.618573,104.928643,yes,yes,3.000000,3.000000,Sometimes,no,1.698767,no,0.000000,0.543960,Sometimes,Public_Transportation,Obesity_Type_III
820,Female,32.997118,1.672446,74.812707,yes,yes,2.948425,1.198643,Sometimes,no,1.000000,no,0.000000,0.173796,Sometimes,Automobile,Overweight_Level_I
2026,Female,21.838323,1.758959,137.792990,yes,yes,3.000000,3.000000,Sometimes,no,2.640539,no,1.879818,0.885993,Sometimes,Public_Transportation,Obesity_Type_III
692,Male,18.000000,1.767058,51.132809,yes,yes,2.708965,3.000000,Sometimes,no,1.873004,no,1.217180,1.000000,Sometimes,Public_Transportation,Insufficient_Weight
454,Female,20.000000,1.680000,68.000000,no,yes,3.000000,1.000000,Sometimes,no,1.000000,no,1.000000,0.000000,no,Public_Transportation,Normal_Weight
875,Female,16.865984,1.644053,67.439589,yes,yes,1.314150,1.068196,Sometimes,no,1.364957,yes,0.000000,0.057926,no,Public_Transportation,Overweight_Level_I
1522,Male,28.363149,1.793476,112.725005,yes,yes,1.991240,3.000000,Sometimes,no,2.000000,no,0.000000,0.292956,Sometimes,Public_Transportation,Obesity_Type_II

In [114]:
obesity_data.columns.to_list()

['Gender',
 'Age',
 'Height',
 'Weight',
 'family_history',
 'FAVC',
 'FCVC',
 'NCP',
 'CAEC',
 'SMOKE',
 'CH2O',
 'SCC',
 'FAF',
 'TUE',
 'CALC',
 'MTRANS',
 'Obesity']

In [115]:
list(obesity_data.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

In [116]:
obesity_data.shape

(2111, 17)

In [117]:
obesity_data.size

35887

In [118]:
obesity_data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [119]:
obesity_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender          2111 non-null   object
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object
 5   FAVC            2111 non-null   object
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object
 9   SMOKE           2111 non-null   object
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object
 15  MTRANS          2111 non-null   object
 16  Obesity         2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [120]:
obesity_data.loc[0:10,'Age':'FAF']

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0

In [121]:
obesity_data.loc[:20,'Age':'FAF'] #For all the rows using this range of columns

,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0
5,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0
6,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
7,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0
8,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0
9,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0
10,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0
11,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0
12,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0
13,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0
14,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0
15,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0
16,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0
17,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0
18,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0
19,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0
20,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0

In [122]:
obesity_data.iloc[0:10,0:5]

   Gender   Age  Height  Weight family_history
0  Female  21.0    1.62    64.0            yes
1  Female  21.0    1.52    56.0            yes
2    Male  23.0    1.80    77.0            yes
3    Male  27.0    1.80    87.0             no
4    Male  22.0    1.78    89.8             no
5    Male  29.0    1.62    53.0             no
6  Female  23.0    1.50    55.0            yes
7    Male  22.0    1.64    53.0             no
8    Male  24.0    1.78    64.0            yes
9    Male  22.0    1.72    68.0            yes

loc Collects data may be its string or numerical but iloc always take numerical value

In [123]:
obesity_data.iloc[[10,20,30],[0,1,2]]

   Gender   Age  Height
10   Male  26.0    1.85
20   Male  22.0    1.65
30   Male  29.0    1.77

In [124]:
obesity_data.at[0,'Age']

np.float64(21.0)

In [125]:
obesity_data.iat[0,0]

'Female'

In [126]:
obesity_data['Age']

0       21.000000
1       21.000000
2       23.000000
3       27.000000
4       22.000000
          ...
2106    20.976842
2107    21.982942
2108    22.524036
2109    24.361936
2110    23.664709
Name: Age, Length: 2111, dtype: float64

In [127]:
obesity_data.loc[(obesity_data['Weight']<50) & (obesity_data['Obesity']=='Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking,Normal_Weight
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.0,1.50,44.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
60,Female,21.0,1.55,49.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
94,Female,24.0,1.60,48.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
113,Female,22.0,1.50,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Walking,Normal_Weight
156,Female,35.0,1.53,45.0,yes,no,3.0,3.0,Frequently,no,1.0,no,0.0,1.0,no,Automobile,Normal_Weight
176,Female,18.0,1.57,48.0,yes,yes,3.0,1.0,Always,no,1.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
180,Female,18.0,1.58,48.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
218,Female,21.0,1.50,42.3,yes,no,1.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Public_Transportation,Normal_Weight
234,Female,19.0,1.59,49.0,yes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
244,Female,21.0,1.54,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,yes,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
253,Female,26.0,1.59,47.0,yes,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
303,Female,16.0,1.57,49.0,no,yes,2.0,4.0,Always,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
307,Female,23.0,1.59,48.0,yes,yes,2.0,1.0,Frequently,no,1.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
318,Female,25.0,1.56,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
346,Female,21.0,1.54,47.0,yes,no,3.0,3.0,Always,no,1.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
359,Female,33.0,1.56,48.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
385,Female,16.0,1.55,45.0,no,yes,2.0,3.0,Frequently,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
445,Female,19.0,1.51,45.0,no,yes,2.0,4.0,Sometimes,no,1.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
457,Female,19.0,1.50,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [128]:
obesity_data[(obesity_data['Weight']<50) & (obesity_data['Obesity']=='Normal_Weight')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking,Normal_Weight
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
51,Female,20.0,1.50,44.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
60,Female,21.0,1.55,49.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,1.0,Sometimes,Public_Transportation,Normal_Weight
94,Female,24.0,1.60,48.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
113,Female,22.0,1.50,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Walking,Normal_Weight
156,Female,35.0,1.53,45.0,yes,no,3.0,3.0,Frequently,no,1.0,no,0.0,1.0,no,Automobile,Normal_Weight
176,Female,18.0,1.57,48.0,yes,yes,3.0,1.0,Always,no,1.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
180,Female,18.0,1.58,48.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,no,Public_Transportation,Normal_Weight
218,Female,21.0,1.50,42.3,yes,no,1.0,1.0,Sometimes,no,2.0,no,3.0,0.0,no,Public_Transportation,Normal_Weight
234,Female,19.0,1.59,49.0,yes,yes,2.0,1.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
244,Female,21.0,1.54,49.0,yes,no,2.0,1.0,Sometimes,no,2.0,yes,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight
253,Female,26.0,1.59,47.0,yes,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
303,Female,16.0,1.57,49.0,no,yes,2.0,4.0,Always,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
307,Female,23.0,1.59,48.0,yes,yes,2.0,1.0,Frequently,no,1.0,no,0.0,2.0,Sometimes,Public_Transportation,Normal_Weight
318,Female,25.0,1.56,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
346,Female,21.0,1.54,47.0,yes,no,3.0,3.0,Always,no,1.0,no,2.0,0.0,no,Public_Transportation,Normal_Weight
359,Female,33.0,1.56,48.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation,Normal_Weight
385,Female,16.0,1.55,45.0,no,yes,2.0,3.0,Frequently,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight
445,Female,19.0,1.51,45.0,no,yes,2.0,4.0,Sometimes,no,1.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
457,Female,19.0,1.50,45.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [129]:
obesity_data.loc[obesity_data['Obesity'].str.contains('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [130]:
obesity_data[obesity_data['Obesity'].str.contains('Normal')]

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,Male,25.0,1.66,68.0,no,yes,2.0,3.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight
493,Male,20.0,1.80,65.0,no,yes,2.0,3.0,Frequently,no,1.0,no,2.0,0.0,Sometimes,Motorbike,Normal_Weight
494,Female,18.0,1.67,66.0,no,yes,3.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Normal_Weight
495,Male,19.0,1.80,60.0,yes,yes,3.0,1.0,Always,no,1.0,yes,0.0,0.0,no,Motorbike,Normal_Weight
497,Male,20.0,1.56,45.0,no,no,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight

In [131]:
obesity_data.loc[0,'Age']=22

In [132]:
obesity_data.head(1)

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight

In [133]:
obesity_data.loc[:,'SMOKE']='yes'

In [134]:
obesity_data['SMOKE']

0       yes
1       yes
2       yes
3       yes
4       yes
       ...
2106    yes
2107    yes
2108    yes
2109    yes
2110    yes
Name: SMOKE, Length: 2111, dtype: object

In [135]:
obesity_data['SMOKE']

0       yes
1       yes
2       yes
3       yes
4       yes
       ...
2106    yes
2107    yes
2108    yes
2109    yes
2110    yes
Name: SMOKE, Length: 2111, dtype: object

In [136]:
obesity_data.loc[[2,3],'Height']=1.6

In [137]:
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [138]:
def increment(x):
  return x+5
new_df=obesity_data['Age'].apply(increment)
print(new_df)

0       27.000000
1       26.000000
2       28.000000
3       32.000000
4       27.000000
          ...
2106    25.976842
2107    26.982942
2108    27.524036
2109    29.361936
2110    28.664709
Name: Age, Length: 2111, dtype: float64

In [139]:
obesity_data['Age Category']=obesity_data['Age'].apply(lambda x:'Very Young' if x<25 else 'Not so Young')
obesity_data['Age Category']

0         Very Young
1         Very Young
2         Very Young
3       Not so Young
4         Very Young
            ...
2106      Very Young
2107      Very Young
2108      Very Young
2109      Very Young
2110      Very Young
Name: Age Category, Length: 2111, dtype: object

In [140]:
obesity_data.insert(2,'BMI',20)

In [141]:
obesity_data.head(20)

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,22.0,20,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,20,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,20,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,20,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,20,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
5,Male,29.0,20,1.62,53.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight,Not so Young
6,Female,23.0,20,1.50,55.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight,Very Young
7,Male,22.0,20,1.64,53.0,no,no,2.0,3.0,Sometimes,yes,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
8,Male,24.0,20,1.78,64.0,yes,yes,3.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
9,Male,22.0,20,1.72,68.0,yes,yes,2.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
10,Male,26.0,20,1.85,105.0,yes,yes,3.0,3.0,Frequently,yes,3.0,no,2.0,2.0,Sometimes,Public_Transportation,Obesity_Type_I,Not so Young
11,Female,21.0,20,1.72,80.0,yes,yes,2.0,3.0,Frequently,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young
12,Male,22.0,20,1.65,56.0,no,no,3.0,3.0,Sometimes,yes,3.0,no,2.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
13,Male,41.0,20,1.80,99.0,no,yes,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Automobile,Obesity_Type_I,Not so Young
14,Male,23.0,20,1.77,60.0,yes,yes,3.0,1.0,Sometimes,yes,1.0,no,1.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
15,Female,22.0,20,1.70,66.0,yes,no,3.0,3.0,Always,yes,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
16,Male,27.0,20,1.93,102.0,yes,yes,2.0,1.0,Sometimes,yes,1.0,no,1.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Not so Young
17,Female,29.0,20,1.53,78.0,no,yes,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile,Obesity_Type_I,Not so Young
18,Female,30.0,20,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile,Overweight_Level_II,Not so Young
19,Female,23.0,20,1.65,70.0,yes,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_I,Very Young

In [142]:
obesity_data.drop(columns='BMI',inplace=True)
obesity_data.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,22.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [143]:
obesity_data.insert(2,'BMI',obesity_data['Weight']/obesity_data['Height']**2)

In [144]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Age Category
0,Female,22.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,30.078125,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [145]:
obesity_data.rename(columns={'Obesity':'Obesity Category'},inplace=True)
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,22.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,30.078125,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [146]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Swap','Shru','Raj','Esh']
})
df2=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Deb','Pri','Rum','Haim']
})
inner_result=pd.merge(df1,df2,how='inner',on='id')
inner_result

   id name_x name_y
0   1   Swap    Deb
1   2   Shru    Pri
2   3    Raj    Rum
3   4    Esh   Haim

In [147]:
df3=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Swap','Shru','Raj','Esh']
})
df4=pd.DataFrame({
    'id':[5,6,7,8],
    'name':['Deb','Pri','Rum','Haim']
})
inner_result=pd.merge(df3,df4,how='outer',on='id')
inner_result

   id name_x name_y
0   1   Swap    NaN
1   2   Shru    NaN
2   3    Raj    NaN
3   4    Esh    NaN
4   5    NaN    Deb
5   6    NaN    Pri
6   7    NaN    Rum
7   8    NaN   Haim

In [148]:
left_result=pd.merge(df3,df4,how='left',on='id')
left_result

   id name_x name_y
0   1   Swap    NaN
1   2   Shru    NaN
2   3    Raj    NaN
3   4    Esh    NaN

In [149]:
right_result=pd.merge(df3,df4,how='right',on='id')
right_result

   id name_x name_y
0   5    NaN    Deb
1   6    NaN    Pri
2   7    NaN    Rum
3   8    NaN   Haim

In [150]:
df5=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Swap','Shru','Raj','Esh']
})
df6=pd.DataFrame({
    'id':[5,6,7,8],
    'name':['Deb','Pri','Rum','Haim']
})
result=pd.concat([df5,df6],axis=0)
result

   id  name
0   1  Swap
1   2  Shru
2   3   Raj
3   4   Esh
0   5   Deb
1   6   Pri
2   7   Rum
3   8  Haim

In [151]:
result1=pd.concat([df5,df6],axis=1)
result1

   id  name  id  name
0   1  Swap   5   Deb
1   2  Shru   6   Pri
2   3   Raj   7   Rum
3   4   Esh   8  Haim

**Null Handling**

In [152]:
result3=pd.concat([df5,df6],axis=0,keys=['df5','df6'])
result3

       id  name
df5 0   1  Swap
    1   2  Shru
    2   3   Raj
    3   4   Esh
df6 0   5   Deb
    1   6   Pri
    2   7   Rum
    3   8  Haim

In [153]:
inner_result

   id name_x name_y
0   1   Swap    NaN
1   2   Shru    NaN
2   3    Raj    NaN
3   4    Esh    NaN
4   5    NaN    Deb
5   6    NaN    Pri
6   7    NaN    Rum
7   8    NaN   Haim

In [154]:
inner_result.isna()

      id  name_x  name_y
0  False   False    True
1  False   False    True
2  False   False    True
3  False   False    True
4  False    True   False
5  False    True   False
6  False    True   False
7  False    True   False

In [155]:
inner_result.notna()

     id  name_x  name_y
0  True    True   False
1  True    True   False
2  True    True   False
3  True    True   False
4  True   False    True
5  True   False    True
6  True   False    True
7  True   False    True

In [156]:
inner_result.isna().sum()

id        0
name_x    4
name_y    4
dtype: int64

In [157]:
import numpy as np
obesity_data.loc[0,'Age']=np.nan
obesity_data.loc[0,'SMOKE']=np.nan
obesity_data.loc[2,'family_history']=np.nan

In [158]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,NaN,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,30.078125,1.60,77.0,NaN,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [159]:
obesity_data.fillna(0,inplace=True)

In [160]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,0.0,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,0,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.0,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.0,30.078125,1.60,77.0,0,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.0,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.0,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [161]:
import numpy as np
obesity_data.loc[0,'Age']=np.nan
obesity_data.loc[0,'SMOKE']=np.nan
obesity_data.loc[2,'family_history']=np.nan

In [162]:
obesity_data['Age'].fillna(obesity_data['Age'].mean(),inplace=True)
obesity_data.head()

/tmp/ipython-input-398673981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  obesity_data['Age'].fillna(obesity_data['Age'].mean(),inplace=True)

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,24.31417,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,NaN,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.00000,30.078125,1.60,77.0,NaN,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.00000,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.00000,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [164]:
obesity_data['SMOKE'].fillna(obesity_data['SMOKE'].mode()[0],inplace=True)
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,24.31417,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.00000,30.078125,1.60,77.0,NaN,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.00000,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.00000,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [165]:
obesity_data['family_history'].fillna(obesity_data['family_history'].mode()[0],inplace=True)
obesity_data.head()

/tmp/ipython-input-4062521585.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  obesity_data['family_history'].fillna(obesity_data['family_history'].mode()[0],inplace=True)

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,24.31417,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.00000,30.078125,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.00000,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.00000,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [166]:
#dropna,interpolate etc use for replacing NaN

In [169]:
obesity_data.groupby('Gender').count()

,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
Gender,,,,,,,,,,,,,,,,,,
Female,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043,1043
Male,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068,1068

In [168]:
obesity_data.head()

,Gender,Age,BMI,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity Category,Age Category
0,Female,24.31417,24.386526,1.62,64.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,Very Young
1,Female,21.00000,24.238227,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,Very Young
2,Male,23.00000,30.078125,1.60,77.0,yes,no,2.0,3.0,Sometimes,yes,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,Very Young
3,Male,27.00000,33.984375,1.60,87.0,no,no,3.0,3.0,Sometimes,yes,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,Not so Young
4,Male,22.00000,28.342381,1.78,89.8,no,no,2.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,Very Young

In [170]:
obesity_data.groupby('Gender')['Height'].mean()

Gender
Female    1.643298
Male      1.758316
Name: Height, dtype: float64

In [171]:
obesity_data.groupby('Gender')['Height'].median()

Gender
Female    1.639524
Male      1.760000
Name: Height, dtype: float64

In [172]:
obesity_data.groupby('Gender')['Height'].agg('sum','mean')

Gender
Female    1713.959615
Male      1877.881278
Name: Height, dtype: float64